#!/bin/bash

filename=`date +"%Y-%m-%d"`-`echo ${1// /-} | tr '[A-Z]' '[a-z]'`.textile
if [ -e _posts/$filename ]; then
  echo "Post already exists!"
  exit
fi
echo $filename
echo "---" > _posts/$filename
echo "layout: post" >> _posts/$filename
echo "title: $1" >> _posts/$filename
echo "---" >> _posts/$filename

